global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # Scrape da API rodando no serviço Docker "api"
  - job_name: tech-challenge-api-docker
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8000']

# Observação:
# Removemos qualquer job "tech-challenge-api-local" (ex: localhost:8000),
# pois dentro do container do Prometheus, "localhost" aponta para o próprio Prometheus,
# não para a API no host.
